# Generated by Django 2.2.17 on 2020-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
        ),
    ]
