# Generated by Django 2.2.17 on 2020-11-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countymapperapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('county_name', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=10)),
            ],
        ),
    ]
