# Generated by Django 2.2.17 on 2020-11-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countymapperapp', '0002_offense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='offense',
            name='run',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='countymapperapp.ParseBatch'),
            preserve_default=False,
        ),
    ]
