# Generated by Django 2.2.17 on 2020-11-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countymapperapp', '0004_precipitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=8, max_digits=10)),
                ('units', models.CharField(max_length=50)),
                ('fips_code', models.CharField(max_length=10)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countymapperapp.ParseBatch')),
            ],
        ),
    ]
